server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
            - Method=GET, POST
        - id: collecting-service
          uri: lb://COLLECTING-SERVICE
          predicates:
            - Path=/collecting-service/**
            - Method=GET, POST
        - id: inspection-service
          uri: lb://INSPECTION-SERVICE
          predicates:
            - Path=/inspection-service/**
            - Method=GET, POST
        - id: prescribe-service
          uri: lb://PRESCRIBE-SERVICE
          predicates:
            - Path=/prescribe-service/**
            - Method=GET, POST

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, trace, busrefresh