server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      routes:
        - id:
          uri:
          predicates:
            - Path=/user-service/**
            - Method=GET, POST

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, trace, busrefresh